# CI build script for Travis.
# See https://docs.travis-ci.com/user/multi-os/ for more info.

os: osx

language: ruby

#branches:
#  only:
#  - master
#  # Enable building of tags.
#  - /2.0.*/

install: sudo gem install asciidoctor

before_script:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - ./install-gitconfig.sh
  - rm TODO.md
  - git checkout TODO.md

script:
  - make

deploy:
  provider: pages
  edge: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: out
  on:
    tags: true
