#!/usr/bin/env ruby
# Copyright (c) 2020 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

require 'fileutils'
require 'json'
require 'set'
formats = JSON.parse(File.read('formats.json'), :symbolize_names => true).freeze
targets = [:glFormat, :glType, :glInternalFormat, :dxgiFormat, :mtlFormat].freeze
HEADER = %{// Copyright 2020 The Khronos Group Inc.
// SPDX-License-Identifier: Apache-2.0

/*************************************** Do not edit ***************************************
                                  Automatically generated by
  https://github.com/KhronosGroup/KTX-Specification/blob/master/generate_format_switches.rb
 *******************************************************************************************/
}

dir = FileUtils.mkdir_p(ARGV.fetch(0, 'out'))[0]
files = targets.map { |t| [t, File.open("#{dir}/vkFormat2#{t}.inl", 'w')] }.to_h.freeze
files.values.each { |file| file << HEADER }
formats.each do |format|
  files.each do |target, file|
    file << "case #{format[:vkFormat]}: return #{format[target]};\n" if format[target]
  end
end
files.values.each(&:close)

# Some consumers may need a DXGI -> VkFormat switch (e.g., converting DDS to KTX2)
dxgi2vkformat_file = File.open("#{dir}/dxgiFormat2vkFormat.inl", 'w')
already_added_enum_values = Set[]
formats.each do |format|
  # Here we assume that the first encountered DXGI-to-VkFormat conversion is the
  # most suitable DXGI-to-VkFormat conversion. Without this check we will end up
  # with multiple similar case statements on same DXGI enum values because
  # 'formats.json' is used to map VkFormat to other formats and can, therefore,
  # map to same DXGI value multiple times (e.g., DXGI_FORMAT_R8G8B8A8_UNORM)
  if format[:dxgiFormat] and already_added_enum_values.add?(format[:dxgiFormat])
    dxgi2vkformat_file << "case #{format[:dxgiFormat]}: return #{format[:vkFormat]};\n"
  end
end
dxgi2vkformat_file.close()
