[appendix#basisuah66i]
[#basisuah66i_bitstream]
== Basis UASTC HDR 6x6 Intermediate Bitstream Specification

_Basis UASTC HDR 6x6 Intermediate_ is a custom supercompression scheme for the Basis UASTC HDR 6x6 texture format.

The bitstream is as documented in the https://github.com/BinomialLLC/basis_universal/wiki/UASTC-HDR-6x6-Intermediate-File-Format-(Basis-GPU-Photo-6x6)[format specification] on the basis_universal Wiki, except that the https://github.com/BinomialLLC/basis_universal/wiki/UASTC-HDR-6x6-Intermediate-File-Format-(Basis-GPU-Photo-6x6)#header[header] is not included when the bitstream is contained in a KTX v2 file. The compression type is signalled by `supercompressionScheme` = 4 and `colorModel` = 168. The image width and height can be calculated using <<levelImages_defs,these formulae>> for stem:[\textit{num_blocks_x}] and stem:[\textit{num_blocks_y}] with stem:[\textit{block_width}] and stem:[\textit{block_height}] stem:[1]. The number of unpacked ASTC HDR 6x6 blocks can be calculated using the <<levelImages_defs,same formulae>> but with stem:[\textit{block_width}] and stem:[\textit{block_height}] stem:[6] then calculating stem:[\textit{num_blocks_x}\times\textit{num_blocks_y}].


// vim: filetype=asciidoc ai expandtab tw=0 ts=4 sts=2 sw=2
