[appendix#basisxual_gd]
== Basis XUASTC LDR Global Data

The Basis XUASTC LDR format combines encoding to a subset of ASTC LDR, that can be easily transcoded to ASTC or BC7, with DCT based supercompression of the ASTC logical block parameters.

Because of the variable size of each image, Basis XUASTC LDR creates a global data structure that contains an array of _image descriptors_ with the offset within its mip level and the length of the data for that image.


[[basisxual_global_data_structure]]
.Basis XUASTC LDR Global Data Structure
[source,c,subs="+quotes,+attributes,+replacements"]
----
ImageDesc[imageCount] imageDescs;
----

`ImageDesc` is the following structure.

.ImageDesc
[source,c]
----
UInt32 rgbaSliceByteOffset
UInt32 rgbaSliceByteLength
UInt32 sliceProfile
----

Descriptions in the `imageDescs` array are in the order layer, face and z_slice as if arranged by the following pseudo code.
[source,c]
----
for each level in max(levelCount, 1)
    for each layer in max (layerCount, 1)
        for each face in faceCount // 1 or 6
            for each z_slice in max((pixelDepth of level), 1)
----

`imageCount` is the total number of images in the Mip Level Array.

[TIP]
====
`imageCount` may be calculated as follows:
[source,c]
----
int imageCount = max(layerCount, 1) * faceCount * layerPixelDepth;

// where layerPixelDepth can be derived as
int layerPixelDepth = max(pixelDepth, 1);
for(int i = 1; i < levelCount; i++)
    layerPixelDepth += max(pixelDepth >> i, 1);
----
====

There must be no trailing bytes in the global data section after the array of image descriptors, i.e., the following condition must always be true:
[source,c]
----
sgdByteLength == imageCount * 12
----

[[basisxual_image_desc]]
=== ImageDesc
==== rgbaSliceByteOffset, rgbaSliceByteLength
The offset of the start of the slice within the <<levelImagesDesc,levelImages>> of its mip level and its byte length. The offset of <<levelImagesDesc,levelImages>> within the file is given in the <<_level_index,Level Index>>.

`rgbaSliceByteLength` must not be zero.

`rgbaSliceByteOffset + rgbaSliceByteLength` must not be greater than the byte length of the corresponding mip level.

[[basisxual_sliceProfile]]
==== sliceProfile
The profile field containing the entropy profile and codec variant used in the bitstream for this slice.
The entropy profile used by the slice is given in bits 0-7, the first byte.
Three profiles are currently known: Full Arithmetic (1), Hybrid (2), and Full Zstd (3).
The codec variant is given in bits 8-15, the second byte.
One variant is currently known, signalled by the value 1.

The entropy profile, the first byte, must match the first byte of a slice's bitstream.
The codec variant value must match the 5-bit _Stream Version_ found at the start of the _System Header_ which begins at the second byte of a slice's bitstream in all profiles.
The Full Arithmetic and Hybrid profiles' _System Header_ is described https://github.com/BinomialLLC/basis_universal/wiki/XUASTC-LDR-Arithmetic-Profile[here].
The Full Zstd profile's uses the same _System Header_ though the description is repeated in the Full Zstd bitstream documentation.
The most significant 16-bits (the last two bytes) must be 0.
Implementations must fail gracefully when encountering an unknown profile or codec variant.
[NOTE]
.Rationale
====
Implementations can use this field to check for an unsupported version without having to load the data.
====

// vim: filetype=asciidoc ai expandtab tw=0 ts=4 sts=2 sw=2
