# Copyright 2015-2020 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0
name: KTX-Specification Build CI

on:
  # Trigger the workflow on a pull request,
  pull_request:

  push:
    # And on pushes to main, which will occur when a PR is merged.
    branches:
      - main
      - action-develop
    # Also trigger on push of release tags to any branch. Useful
    # for testing release builds before merging to main.
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    paths-ignore:
      - .appveyor.yml
      - .travis.yml

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-specs:
    name: Build KTX File Format and KTX Fragment URI specifications
    runs-on: ubuntu-latest

    env:
      GIT_LFS_SKIP_SMUDGE: 1
      WERROR: ON

    steps:
    - uses: actions/checkout@v4

    - name: Install Asciidoctor
      run: sudo apt-get install -y asciidoctor

#    - name: Force fetch provoking tag's annotation.
#      # Work around https://github.com/actions/checkout/issues/290.
#      if: github.ref_type == 'tag'
#      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

    - name: Build specs
      run: make

#    - name: Upload To Pages
#      uses: softprops/action-gh-release@v1
#      if: github.event_name == 'push' && github.ref_type == 'tag'
#      with:
#        draft: true
#        prerelease: true
#        files:  KTX-Software-${{env.KTX_VERSION}}-Android.zip*
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Deploy job
  deploy:
    name: Deploy to GitHub Pages
    # Add a dependency to the build job
    needs: build-specs
    # Only deploy when building `main`.
    if: github.ref == 'refs/heads/main'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
